name: Build Android Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Build Android Release
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
          cd android && ./gradlew assembleRelease
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-release
          path: android/app/build/outputs/apk/release/app-release.apk
